#---
# Title: role-mariadb-docker
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/01-mariadb-docker.yml
#
# Description:
#   This is the main file of the role.
#
- name: "Install APT packages"
  ansible.builtin.apt:
    name: "{{ packages.name }}"
    state: present
    update_cache: yes
  loop:
    - { name: 'python3-docker', desc: 'Python for docker' }
  loop_control:
    loop_var: packages

- name: "Start MariaDB Docker container"
  docker_container:
    name: "{{ mariadb_docker_container_name }}"
    image: "mariadb:{{ mariadb_docker_image_tags }}"
    restart_policy: always
    env:
      MARIADB_ROOT_PASSWORD: "{{ mariadb_root_password }}"
      MARIADB_DATABASE: "{{ mariadb_database }}"
      MARIADB_USER: "{{ mariadb_user }}"
      MARIADB_PASSWORD: "{{ mariadb_password }}"
      #MARIADB_ROOT_PASSWORD_FILE: ~/.env
      #MYSQL_MAX_ALLOWED_PACKET: 256M
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - "{{ mariadb_backup_path }}:{{ mariadb_backup_path }}"
    ports:
      - "3306:3306"
    container_default_behavior: no_defaults
    
- name: Wait for MariaDB to start
  wait_for:
    host: 127.0.0.1
    port: 3306
    delay: 5
    timeout: 60
