#---
# Title: role-mariadb-docker
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/main.yml
#
# Description:
#   This is the main file of the role.
#
 #   - name: "Include tasks/01-base.yml"
 #     include_tasks: tasks/01-base.yml
