#---
# Title: role-mariadb-docker
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/main.yml
#
# Description:
#   This is the main file of the role.
#
- name: "Include tasks/01-mariadb-docker.yml for installing MariaDB server"
  include_tasks: tasks/01-mariadb-docker.yml

- name: "Include tasks/02-phpmyadmin-docker.yml for installing PHPMyAdmin for MariaDB"
  include_tasks: 02-phpmyadmin-docker.yml
  
- name: "Include tasks/03-mariadb-backup.yml for installing PHPMyAdmin for MariaDB"
  include_tasks: 03-mariadb-backup.yml
